### ISSUE TITLE
Plugin is incompatible with Redmine 4.x a.k.a. undefined method `alias_method_chain' for SysController:Class

### ISSUE THREAD

**Issue by e2-online** [lpirl/redmine_scm_hookhelpers#4]
When booting Redmine 4.0.3 I get this message:
```
NoMethodError: undefined method `alias_method_chain' for SysController:Class
Did you mean?  alias_method
/usr/src/redmine/plugins/redmine_scm_hookhelpers/lib/sys_controller_patch.rb:9:in `block in included'
/usr/src/redmine/plugins/redmine_scm_hookhelpers/lib/sys_controller_patch.rb:8:in `class_eval'
/usr/src/redmine/plugins/redmine_scm_hookhelpers/lib/sys_controller_patch.rb:8:in `included'
/usr/src/redmine/plugins/redmine_scm_hookhelpers/init.rb:14:in `include'
/usr/src/redmine/plugins/redmine_scm_hookhelpers/init.rb:14:in `block in <top (required)>'
```

I've read the underlying Rails changed a bit. Do you know how to solve this issue?

**Comment by lpirl** [comment]
Thanks for the report @e2-online .
Unfortunately, I personally don't use this plugin anymore.
If you (or anyone) is willing to dig into this, I am more than happy to take PRs.

**Comment by e2-online** [comment]
Which plugin do you use instead?
I stumbled upon [GitMirror](https://redmine.org/plugins/redmine_git_mirror), which looks promising.

**Comment by lpirl** [comment]
None, I am sorry. This plugin is used in a Redmine instance I maintained for my employer. Maybe my successor will contribute a fix, I already sent him a note regarding this issue.
Otherwise, still, feel free to dig in. :)

**Comment by quanterium** [comment]
I ran into this when upgrading my Redmine installation to a newer server, which included finally moving from Redmine 2 to Redmine 4. I just submitted a PR #5 with the fix that seems to be working for me.

**Comment by lpirl** [comment]
Kudos to @quanterium for fixing this.
